{% set name = "purpose" %}
{% set version = "5.74.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.kde.org/stable/frameworks/{{ major_minor }}/purpose-{{ version }}.tar.xz
  sha256: 1f65696558e82808b2beb3715da2e833a6e1f214f33bcc670ef0f023bb044205

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('purpose', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - extra-cmake-modules >={{ major_minor }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
  host:
    - xorg-libxfixes  # [linux]
    - xorg-libxext
    - qt
    - kirigami2 >={{ major_minor }}
    - kio >={{ major_minor }}
    - ki18n >={{ major_minor }}
    - kconfig >={{ major_minor }}
    #- kaccounts (optional, for youtube only)
    - kcoreaddons >={{ major_minor }}
    - knotifications >={{ major_minor }}

test:
  commands:
    - test -f ${PREFIX}/lib/libKF5Purpose.so

about:
  home: https://api.kde.org/frameworks/purpose/html/index.html
  license: GPL-2.0-or-later AND LGPL-2.0-or-later AND LGPL-2.1-or-later
  license_file:
    - LICENSES/GPL-2.0-or-later.txt
    - LICENSES/LGPL-2.0-or-later.txt
    - LICENSES/LGPL-2.1-or-later.txt
  summary: Offers available actions for a specific purpose
  description: |
    This framework offers the possibility to create integrate services
    and actions on any application without having to implement them
    specifically. Purpose will offer them mechanisms to list the different
    alternatives to execute given the requested action type and will facilitate
    components so that all the plugins can receive all the information they need.
  dev_url: https://cgit.kde.org/purpose.git/tree

extra:
  recipe-maintainers:
    - scopatz
