travis:
  secure:
    BINSTAR_TOKEN: LPRdJHaL3tBOuT9HoRg8WKTFGYPNhHpXkAgLPQKQpLOgjNb1RPZCxVReNg891GlUI+i2i6tfZLpsgvX5tvHf/TAoz3JIz+crJNwY/f73/Q2rbdXXKi+PFGu9N9DqWnMjejn58K3oBotIFMCcFlGNk3nftuZJXtWdS7JXfMSJCLfSD9FtEIr0U7tgB2cYXhCBbtPpsWzjtX2og9CmmC7ZciK5cd3HQM5ZftQZiRzKZ8leRCTajTFmirsf3QATsyP4M0I5BS/wYSV093fANUsEgAVGRaonKZwoT1f0h9kLuA50sF2eW4mcVqCgWdJAfDjdjZb2TbZSDkDi3VAQGKTp26SkevaWnNQFq4xAI4kwlQ3/QMS5jZ8sED+Jm5tmXVBvwBPQUtkUL9mwCFIPjEtyi+c8lQP82u2iFyVVRPtbx97psLJC+VddXDF4cfYVU6+k6k3Too280bBAgfHyWhV6esz4Z+ggq2+cG2Mlw9f7VO67+MH+d60nMxMANuQ074e8xkjskwYe3+OvqurwT9o5tRxUI3km6MV2+tVwbU/gp3hZwDgrLrV+yn9cNsIOx8zhXM/GNDgVyMUfIkEQHZq4Hgygzculwn5b0fmpgVm5mEGOyLyK/BOIpJGR+T/iSQzRV3BhYnkbET3Ngm9d6HKPmRidoG+okQ4cA7cfHZo9nGg=
conda_forge_output_validation: true
bot:
  check_solvable: True
  
